sudo: false
language: node_js

node_js:
  - "10"
  - "11"
  - "12"

os:
  - linux

install:
  - npm install
  - npm i -g typescript jest

script: npm run test

branches:
  only:
    - master
    
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
   node: '12'
